using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Builder;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.EntityFrameworkCore;
using System.Threading.Tasks;

namespace SHTWIMS03.Models
{
    public static class CatalogItemSeedData // -----------------------------------------------------------
    {
        public static void EnsurePopulated(IApplicationBuilder app)
        {
            ApplicationDbContext context = app.ApplicationServices.
                GetRequiredService<ApplicationDbContext>();
            context.Database.Migrate();
            if (!context.CatalogItems.Any())
            {
                context.CatalogItems.AddRange(

                new CatalogItem { ItemId = "OS-P950", Description = "ARROW, DIRECTION, DISASTER,  PKG/5", UoM = "PKG", Category = "NSAL " },
                new CatalogItem { ItemId = "OS-D283", Description = "ARROWS PKG/10", UoM = "PKG", Category = "NSAL " },
                new CatalogItem { ItemId = "OS-D2008", Description = "BABY FORMULA", UoM = "Ea", Category = "NSAL " },
                new CatalogItem { ItemId = "BD-D125", Description = "BACKPACK, DISASTER RECOVERY", UoM = "Ea", Category = "NSAL " },
                new CatalogItem { ItemId = "KF-D46N", Description = "BAG SANDWICH, NON-STANDARD, PACKAGE QTYS VARY", UoM = "PKG", Category = " " },
                new CatalogItem { ItemId = "KF-D46", Description = "BAG, SANDWICH PKG/1000", UoM = "PKG", Category = " " },
                new CatalogItem { ItemId = "BD-D275", Description = "BAG, Trash Bag, 30 gal, 15/box or var -IKD", UoM = "Bx", Category = "NSAL IKD " },
                new CatalogItem { ItemId = "BD-D274", Description = "BAG, Trash Bag, Can liners, 25/roll, 10 roll/cs or var  -IKD", UoM = "Cs", Category = "NSAL IKD " },
                new CatalogItem { ItemId = "BD-D324", Description = "BAG, Trash, Kitchen-size (30 gal) box/cs qtys vary", UoM = "Box", Category = "Trl Short NSAL " },
                new CatalogItem { ItemId = "BD-D273", Description = "BAG, Trash, Large-size box/cs qtys vary", UoM = "Box", Category = "Short NSAL " },
                new CatalogItem { ItemId = "Trl-005", Description = "Ball, trailer hitch for towing, stored in trailer", UoM = "ea", Category = "Trl " },
                new CatalogItem { ItemId = "OS-D275", Description = "BANNER, DISASTER RELIEF, 10X3", UoM = "Ea", Category = "Short NSAL " },
                new CatalogItem { ItemId = "OS-D277", Description = "BANNER, DISASTER RELIEF, 5X3 PKG/5", UoM = "PKG", Category = "Short Trl NSAL " },
                new CatalogItem { ItemId = "OS-D274", Description = "BANNER, SHELTER, 10X3", UoM = "Ea", Category = "Short NSAL " },
                new CatalogItem { ItemId = "OS-D276", Description = "BANNER, SHELTER, 5X3 PKG/5", UoM = "PKG", Category = "Short NSAL " },
                new CatalogItem { ItemId = "KF-D68", Description = "BANQUET PACK CS/250", UoM = "CS", Category = "Short Trl NSAL " },
                new CatalogItem { ItemId = "KF-D68N", Description = "BANQUET PACK, NON-STANDARD, CASE QTYS VARY", UoM = "CS", Category = "NSAL " },
                new CatalogItem { ItemId = "BD-D2639V", Description = "BATTERIES  9 VOLT", UoM = "Ea", Category = "Prep " },
                new CatalogItem { ItemId = "BD-D263AA", Description = "BATTERIES  AA CELL", UoM = "Ea", Category = "NSAL " },
                new CatalogItem { ItemId = "BD-D263C", Description = "BATTERIES  C CELL", UoM = "Ea", Category = " " },
                new CatalogItem { ItemId = "BD-D263D", Description = "BATTERIES  D CELL", UoM = "Ea", Category = "Prep Short NSAL " },
                new CatalogItem { ItemId = "BD-D263AAA", Description = "BATTERIES AAA CELL", UoM = "Ea", Category = " " },
                new CatalogItem { ItemId = "BD-262AA4", Description = "Battery - IKD, AA 4 Ea/pk", UoM = "pkg", Category = "NSAL IKD " },
                new CatalogItem { ItemId = "BD-262AA8", Description = "Battery - IKD, AA 8 Ea/pk", UoM = "ea", Category = "NSAL IKD " },
                new CatalogItem { ItemId = "BD-D262D", Description = "Battery - IKD, D cell, var pack size 2 or 4 ea", UoM = "ea", Category = "NSAL IKD " },
                new CatalogItem { ItemId = "Trl-020", Description = "Beverage container dual storage, (?KF-D41)", UoM = "ea", Category = "Trl NSAL " },
                new CatalogItem { ItemId = "SS-D37", Description = "BLANKET, NATIONAL STANDARD, WHITE W/ ARC LOGO", UoM = "Ea", Category = "Short Trl DAT NSAL " },
                new CatalogItem { ItemId = "SS-D37N", Description = "BLANKET, NON-STANDARD", UoM = "Ea", Category = " " },
                new CatalogItem { ItemId = "BD-A3013", Description = "BOOKLET, MOVING FORWARD AFTER DISASTER PKG/25", UoM = "PKG", Category = "Short NSAL " },
                new CatalogItem { ItemId = "BD-A3013S", Description = "BOOKLET, MOVING FORWARD AFTER DISASTER, SPANISH PKG/25", UoM = "PKG", Category = "Short NSAL " },
                new CatalogItem { ItemId = "BD-A1569", Description = "BROCHURE, EMERGENCY ASSISTANCE VISUAL LANGUAGE TRANSLATOR", UoM = "Ea", Category = "NSAL " },
                new CatalogItem { ItemId = "BD-A1567", Description = "BROCHURE, MEDICAL VISUAL LANGUAGE TRANSLATOR", UoM = "Ea", Category = "NSAL " },
                new CatalogItem { ItemId = "BD-A1567S", Description = "BROCHURE, SPANISH MEDICAL VISUAL LANGUAGE TRANSLATOR", UoM = "Ea", Category = "NSAL " },
                new CatalogItem { ItemId = "BD-D183", Description = "BUCKET, PLASTIC", UoM = "Ea", Category = "NSAL " },
                new CatalogItem { ItemId = "DT-007", Description = "Carbon Monoxide detector", UoM = "ea", Category = "Prep " },
                new CatalogItem { ItemId = "OS-F5897", Description = "CARD, DISASTER SERVICE ONLY, WHITE PKG/50", UoM = "PKG", Category = " " },
                new CatalogItem { ItemId = "OS-F5867", Description = "CARD, INDEX, OPEN ADDITIONAL ASSISTANCE CASE FILE, BLUE PKG/50", UoM = "PKG", Category = " " },
                new CatalogItem { ItemId = "OS-F5868", Description = "CARD, INDEX, OPEN ADDITIONAL ASSISTANCE CASE FILE, LIGHT GREEN PKG/50", UoM = "PKG", Category = " " },
                new CatalogItem { ItemId = "KF-D41", Description = "CARRIER, DRINK/BEVERAGE", UoM = "Ea", Category = "NSAL " },
                new CatalogItem { ItemId = "KF-D43", Description = "CARRIER, FOOD, LARGE", UoM = "Ea", Category = "NSAL " },
                new CatalogItem { ItemId = "KF-D124", Description = "CARRIER, FOOD, SMALL", UoM = "Ea", Category = "NSAL " },
                new CatalogItem { ItemId = "OS-D118", Description = "CHAIR", UoM = "Ea", Category = "NSAL " },
                new CatalogItem { ItemId = "SS-D326", Description = "CHAIR, SHOWER", UoM = "Ea", Category = "NSAL " },
                new CatalogItem { ItemId = "KF-D196", Description = "CLAMSHELL, NATIONAL STANDARD, 3 COMPARTMENT, CS/200", UoM = "CS", Category = "Short Trl NSAL " },
                new CatalogItem { ItemId = "KF-D196N", Description = "CLAMSHELL, NON-STANDARD, CASE QTYS VARY", UoM = "CS", Category = "NSAL " },
                new CatalogItem { ItemId = "BD-D11", Description = "CLEAN UP KIT/ NATIONAL STANDARD (48 per pallet)", UoM = "Ea", Category = "Short Trl NSAL " },
                new CatalogItem { ItemId = "BD-D11N", Description = "CLEAN-UP KIT / NON-STANDARD", UoM = "Ea", Category = "NSAL " },
                new CatalogItem { ItemId = "OS-D49", Description = "COFFEE MAKER", UoM = "Ea", Category = "Trl " },
                new CatalogItem { ItemId = "OS-A4049", Description = "COIN BOX, W/CABLE, 6X4X4", UoM = "Ea", Category = " " },
                new CatalogItem { ItemId = "SS-D1401", Description = "Comfort Kit, Child, Non-standard", UoM = "ea", Category = " " },
                new CatalogItem { ItemId = "SS-D21U", Description = "COMFORT KIT, NATIONAL STANDARD, UNISEX", UoM = "Ea", Category = "Short Trl DAT NSAL " },
                new CatalogItem { ItemId = "SS-D21UN", Description = "COMFORT KIT, NON-STANDARD", UoM = "Ea", Category = "NSAL " },
                new CatalogItem { ItemId = "SS-D327", Description = "COMMODE RISER, 3-IN-1", UoM = "Ea", Category = "NSAL " },
                new CatalogItem { ItemId = "BD-D308", Description = "COOLER, SIZES VARY", UoM = "Ea", Category = "NSAL " },
                new CatalogItem { ItemId = "SS-D343", Description = "COT, MEDICAL, NATIONAL STANDARD, RATED 450 LB, ADJUSTABLE HEAD/FOOT", UoM = "Ea", Category = "Short Trl NSAL " },
                new CatalogItem { ItemId = "SS-D67", Description = "COT, NATIONAL STANDARD, RATED 350 LB", UoM = "Ea", Category = "Short Trl NSAL " },
                new CatalogItem { ItemId = "SS-D67N", Description = "COT, NON-STANDARD", UoM = "Ea", Category = " " },
                new CatalogItem { ItemId = "BD-KD223", Description = "Crib, Baby -IKD", UoM = "ea", Category = "NSAL IKD " },
                new CatalogItem { ItemId = "KF-KD212", Description = "CUP, CO-BRANDED, RED CROSS/DART CONTAINER, 8-OZ FOAM- CS/1000", UoM = "CS", Category = "NSAL " },
                new CatalogItem { ItemId = "KF-D45N", Description = "CUP, NON-STANDARD, CASE QTYS VARY", UoM = "CS", Category = "Short " },
                new CatalogItem { ItemId = "KF-D45", Description = "CUP, RED CROSS LOGO, CS/1000", UoM = "CS", Category = "Short Trl NSAL " },
                new CatalogItem { ItemId = "OS-D2005", Description = "DAT KIT", UoM = "Ea", Category = " " },
                new CatalogItem { ItemId = "BD-D2010", Description = "DIAPERS, ADULT BRIEFS, SIZES AND PKG QTYS VARY", UoM = "PKG", Category = " " },
                new CatalogItem { ItemId = "BD-D2011", Description = "DIAPERS, BABY, SIZES AND PKG QTYS VARY", UoM = "PKG", Category = " " },
                new CatalogItem { ItemId = "DT-005", Description = "Dual Sensor Alarm, 9V", UoM = "ea", Category = "Obsol " },
                new CatalogItem { ItemId = "Trl-035", Description = "Easel paper pads", UoM = "ea", Category = "Trl " },
                new CatalogItem { ItemId = "SS-D540", Description = "Extension cord", UoM = "ea", Category = "NSAL " },
                new CatalogItem { ItemId = "OS-F1030", Description = "F,FORM, CLIENT ASSISTANCE CARD AUTHORIZATION PKG/50", UoM = "PKG", Category = " " },
                new CatalogItem { ItemId = "OS-F1032", Description = "F,FORM, CLIENT ASSISTANCE CARD CHARGE OUT RECORD PKG/25", UoM = "PKG", Category = " " },
                new CatalogItem { ItemId = "OS-F1031", Description = "F,FORM, DAILY RECORD, CLIENT ASSISTANCE CARD ISSUE PKG/50", UoM = "PKG", Category = " " },
                new CatalogItem { ItemId = "OS-F901", Description = "F,FORM, DISASTER REGISTRATION/CASE RECORD, ENGLISH/SPANISH PKG/50", UoM = "PKG", Category = " " },
                new CatalogItem { ItemId = "OS-F6346", Description = "F,FORM, HOME VISIT ASSIGNMENT SHEET PKG/50", UoM = "PKG", Category = " " },
                new CatalogItem { ItemId = "OS-F5990", Description = "F,FORM, HOME VISIT NOTE PAD/25 EA", UoM = "Ea", Category = " " },
                new CatalogItem { ItemId = "OS-D83", Description = "FAN", UoM = "Ea", Category = " " },
                new CatalogItem { ItemId = "Trl-040", Description = "Fire Extinguisher", UoM = "ea", Category = "Trl " },
                new CatalogItem { ItemId = "BD-D344AA", Description = "FLASHLIGHT WITH AA CELL BATTERIES", UoM = "Ea", Category = " " },
                new CatalogItem { ItemId = "BD-D344AAA", Description = "FLASHLIGHT WITH AAA CELL BATTERIES", UoM = "Ea", Category = " " },
                new CatalogItem { ItemId = "BD-D344C", Description = "FLASHLIGHT WITH C CELL BATTERIES", UoM = "Ea", Category = " " },
                new CatalogItem { ItemId = "BD-D344D", Description = "FLASHLIGHT WITH D CELL BATTERIES", UoM = "Ea", Category = "NSAL " },
                new CatalogItem { ItemId = "BD-D295AA", Description = "FLASHLIGHT, NO BATTERIES, AA CELL", UoM = "Ea", Category = "NSAL " },
                new CatalogItem { ItemId = "BD-D295AAA", Description = "FLASHLIGHT, NO BATTERIES, AAA CELL", UoM = "Ea", Category = " " },
                new CatalogItem { ItemId = "BD-D295C", Description = "FLASHLIGHT, NO BATTERIES, C CELL", UoM = "Ea", Category = " " },
                new CatalogItem { ItemId = "BD-D295D", Description = "FLASHLIGHT, NO BATTERIES, D CELL", UoM = "Ea", Category = "NSAL " },
                new CatalogItem { ItemId = "BD-KD066", Description = "GLOVES, NEOPRENE, NO POWDER, CS/12", UoM = "CS", Category = "NSAL " },
                new CatalogItem { ItemId = "BD-D136", Description = "GLOVES, WORK-VARIOUS SIZES", UoM = "PR", Category = "NSAL " },
                new CatalogItem { ItemId = "BD-KD044", Description = "HAND SANITIZER", UoM = "Ea", Category = "Trl NSAL " },
                new CatalogItem { ItemId = "BD-KD044N", Description = "HAND SANITIZER- NON-STANDARD", UoM = "Ea", Category = " " },
                new CatalogItem { ItemId = "Trl-045", Description = "Hand truck", UoM = "ea", Category = "Trl NSAL " },
                new CatalogItem { ItemId = "OS-320340", Description = "HANG TAG, DISASTER RELIEF", UoM = "Ea", Category = "NSAL " },
                new CatalogItem { ItemId = "OS-D2006", Description = "HEALTH SERVICES KIT", UoM = "Ea", Category = "Short " },
                new CatalogItem { ItemId = "SS-KS225", Description = "IKD-Wheelchair, single axel, flip arms, 265lb capacity", UoM = "ea", Category = "NSAL " },
                new CatalogItem { ItemId = "OS-A4213", Description = "KIT, ID, DISASTER RELIEF", UoM = "Ea", Category = "Short NSAL " },
                new CatalogItem { ItemId = "OS-A4213S", Description = "KIT, ID, DISASTER RELIEF, SPANISH", UoM = "Ea", Category = "Short NSAL " },
                new CatalogItem { ItemId = "OS-P906", Description = "KIT, POSTER, SHELTER INFORMATION, SET/4", UoM = "Ea", Category = "Short NSAL " },
                new CatalogItem { ItemId = "OS-P906S", Description = "KIT, POSTER, SHELTER INFORMATION, SPANISH, SET/4", UoM = "Ea", Category = "Short NSAL " },
                new CatalogItem { ItemId = "KF-D43L", Description = "LINER, FOOD CARRIER LARGE FOR D43, BOX/100", UoM = "Box", Category = "NSAL " },
                new CatalogItem { ItemId = "KF-D124L", Description = "LINER, FOOD CARRIER SMALL, FOR D124, CS/100", UoM = "CS", Category = "NSAL " },
                new CatalogItem { ItemId = "Trl-010", Description = "Lock,  Master Padlock  2-1/2in. keyed alike for region", UoM = "ea", Category = "Trl " },
                new CatalogItem { ItemId = "BD-KD222", Description = "MASK, DUST, 36 PK/CS, 3 EA/PK-TOTAL 108 EA", UoM = "CS", Category = " " },
                new CatalogItem { ItemId = "BD-D2640", Description = "MASK, DUST, 50 EA/BOX", UoM = "Box", Category = "NSAL " },
                new CatalogItem { ItemId = "BD-KD272", Description = "Mask, Dust, N95 rated, -IKD Individually wrapped, var pkg size", UoM = "PKG", Category = "NSAL IKD " },
                new CatalogItem { ItemId = "BD-D319N", Description = "MASK, DUST, NON-STANDARD, BOX QTYS VARY", UoM = "Box", Category = " " },
                new CatalogItem { ItemId = "BD-D268", Description = "MASK, DUST, PACKED 20 BOXES OF 50 EA/CS-TOTAL 1000 EA", UoM = "CS", Category = "NSAL " },
                new CatalogItem { ItemId = "BD-D319", Description = "MASK, DUST, PACKED 8 BOXES OF 30 EA/CS-TOTAL 240 EA", UoM = "CS", Category = " " },
                new CatalogItem { ItemId = "KF-D341A", Description = "MEAL, ENTRÉE ONLY, SHELF STABLE W/HEATER", UoM = "Ea", Category = " " },
                new CatalogItem { ItemId = "KF-D342", Description = "MEAL, KIT, KOSHER/HALAL, NATIONAL STD. SHELF STABLE W/HEATER", UoM = "Ea", Category = "NSAL " },
                new CatalogItem { ItemId = "KF-D250A", Description = "MEAL, KIT, NATIONAL STANDARD, SHELF STABLE W/HEATER", UoM = "Ea", Category = "NSAL " },
                new CatalogItem { ItemId = "KF-D250N", Description = "MEAL, SHELF STABLE, NON-STANDARD", UoM = "Ea", Category = " " },
                new CatalogItem { ItemId = "Trl-025", Description = "Napkins, 1200 count package", UoM = "ea", Category = "Trl " },
                new CatalogItem { ItemId = "DSHKIT-L1", Description = "Nursing Kit (Empty bag)", UoM = "ea", Category = " " },
                new CatalogItem { ItemId = "BD-D2009", Description = "PAPER TOWELS", UoM = "ROL", Category = " " },
                new CatalogItem { ItemId = "OS-320251", Description = "PATCH, ARC, NURSE, EMBROIDERED, IRON ON", UoM = "Ea", Category = " " },
                new CatalogItem { ItemId = "DT-003", Description = "Photoelectric Alarm, 10yr", UoM = "ea", Category = "Obsol " },
                new CatalogItem { ItemId = "PC-005", Description = "Pillow case preparedness activity book, english", UoM = "ea", Category = "Prep " },
                new CatalogItem { ItemId = "PC-006", Description = "Pillow case preparedness activity book, spanish", UoM = "ea", Category = "Prep " },
                new CatalogItem { ItemId = "PC-001", Description = "Pillow case, printed cotton fabric", UoM = "ea", Category = "Prep " },
                new CatalogItem { ItemId = "Trl-075", Description = "Pillow, may be requested by Shelter Manager", UoM = "ea", Category = "Trl " },
                new CatalogItem { ItemId = "OS-321160", Description = "PIN, VOLUNTEER/EMPLOYEE PARTNERSHIP", UoM = "Ea", Category = " " },
                new CatalogItem { ItemId = "OS-P905A", Description = "POSTER, THIS SERVICE TO DISASTER VICTIMS PROVIDED BY, PKG/5", UoM = "PKG", Category = "NSAL " },
                new CatalogItem { ItemId = "OS-D114", Description = "PRESSURE WASHER", UoM = "Ea", Category = " " },
                new CatalogItem { ItemId = "BD-D154", Description = "RAKE, METAL TINES, NATIONAL STANDARD", UoM = "Ea", Category = "NSAL " },
                new CatalogItem { ItemId = "BD-D154N", Description = "RAKE, NON STANDARD", UoM = "Ea", Category = "NSAL " },
                new CatalogItem { ItemId = "BD-D151", Description = "SAFETY GLASSES/GOGGLES", UoM = "Ea", Category = "NSAL " },
                new CatalogItem { ItemId = "Tote-AF", Description = "Shelter forms starter kit form (See also OS-D2007)", UoM = "ea", Category = "Trl " },
                new CatalogItem { ItemId = "Tote-AA", Description = "Shelter Mgmt Starter documents  - Plastic file box with client registration, info and com", UoM = "ea", Category = "Trl " },
                new CatalogItem { ItemId = "Trl-065", Description = "Shelter Starter admin forms, plastic file box", UoM = "ea", Category = "Trl " },
                new CatalogItem { ItemId = "OS-D2007", Description = "SHELTER STARTER KIT", UoM = "Ea", Category = " " },
                new CatalogItem { ItemId = "BD-D306", Description = "SHOVEL, FLAT/TRANSFER, NATIONAL STANDARD", UoM = "Ea", Category = "NSAL " },
                new CatalogItem { ItemId = "BD-D306N", Description = "SHOVEL, NON-STANDARD", UoM = "Ea", Category = "NSAL " },
                new CatalogItem { ItemId = "BD-D315", Description = "SHOVEL, PLASTIC, SNOW", UoM = "Ea", Category = " " },
                new CatalogItem { ItemId = "OS-D316", Description = "SHRINK WRAP ROLLS PER CS VARY", UoM = "CS", Category = "NSAL " },
                new CatalogItem { ItemId = "OS-P949", Description = "SIGN, DISASTER, UTILITY POLE ID, PKG/10", UoM = "PKG", Category = "Short " },
                new CatalogItem { ItemId = "OS-D279", Description = "Sign, YARD SIGN, DISASTER RELIEF  PKG/5", UoM = "PKG", Category = "Short NSAL " },
                new CatalogItem { ItemId = "OS-D278", Description = "Sign, YARD SIGN, SHELTER PKG/5", UoM = "PKG", Category = "Short NSAL " },
                new CatalogItem { ItemId = "OS-DA5070", Description = "SIGNAGE KIT, DRO HEADQUARTERS", UoM = "Ea", Category = "Short NSAL " },
                new CatalogItem { ItemId = "DT-I9010", Description = "Smoke Detector 10 yr Ionization type, P/N 21008697", UoM = "Ea", Category = "Short Prep NSAL " },
                new CatalogItem { ItemId = "DT-001", Description = "Smoke Detector, 9V", UoM = "ea", Category = "Prep " },
                new CatalogItem { ItemId = "KF-DH010", Description = "Snacks, packaged for individual distribution", UoM = "ea", Category = "Trl DAT Short " },
                new CatalogItem { ItemId = "KF-D101", Description = "SPOODLE, SLOTTED 6 OZ", UoM = "Ea", Category = " " },
                new CatalogItem { ItemId = "KF-D100", Description = "SPOODLE, SOLID 8 OZ", UoM = "Ea", Category = " " },
                new CatalogItem { ItemId = "KF-D112", Description = "STEPS, RAIL FOR TRAILER OR BOX TRUCK ACCESS", UoM = "Ea", Category = "NSAL " },
                new CatalogItem { ItemId = "OS-321128", Description = "STICKER, A GIFT FROM THE AMER. RED CROSS, DISASTER RELIEF  ROL/500", UoM = "ROL", Category = "NSAL " },
                new CatalogItem { ItemId = "OS-P128", Description = "STICKER, ARC, 33.5in X 26in  PKG/2", UoM = "PKG", Category = "NSAL " },
                new CatalogItem { ItemId = "OS-320287", Description = "STICKER, WINDOW, STATIC, DISASTER RELIEF- PKG/25", UoM = "PKG", Category = " " },
                new CatalogItem { ItemId = "OS-D117", Description = "TABLE", UoM = "Ea", Category = "NSAL " },
                new CatalogItem { ItemId = "Trl-030", Description = "Tape, blue painter's, individual roll", UoM = "ea", Category = "Trl NSAL " },
                new CatalogItem { ItemId = "OS-KD050", Description = "TAPE, DUCT", UoM = "Ea", Category = "NSAL " },
                new CatalogItem { ItemId = "BD-D282", Description = "TARP, LARGE, SIZES VARY, 26ft x 40ft, 30ft x 60ft, 50ft x 50ft, ETC.", UoM = "Ea", Category = "Trl NSAL " },
                new CatalogItem { ItemId = "BD-D269", Description = "TARP, MEDIUM, SIZES VARY 16ftx 20ft, 18ft x 24ft, 20ft x 20ft, ETC.", UoM = "Ea", Category = "Short NSAL " },
                new CatalogItem { ItemId = "BD-D180", Description = "TARP, SMALL, SIZES VARY 7ft x 5ft, 9ft x 12ft, 12ft x 16ft, ETC.", UoM = "Ea", Category = "NSAL " },
                new CatalogItem { ItemId = "Trl-055", Description = "Toilet seat riser or stand-alone comode", UoM = "ea", Category = "Trl " },
                new CatalogItem { ItemId = "Trl-070", Description = "Tool kit, basic in small toolbox", UoM = "ea", Category = "Trl " },
                new CatalogItem { ItemId = "Tote-A", Description = "Tote Std, Administrative - Supplies for complete DRO admin start up, 28.55in x 19.61in x 15.27in", UoM = "ea", Category = "Trl " },
                new CatalogItem { ItemId = "Tote-S", Description = "Tote Std, Sanitation - Sanitation items for DRO start up, 28.55in x 19.61in x 15.27in", UoM = "ea", Category = "Trl " },
                new CatalogItem { ItemId = "Tote-S&F", Description = "Tote Std, Support and Function Std, Basic humanitarian supplies to kick off client services,  28.55x19.61x15.27", UoM = "ea", Category = "Trl " },
                new CatalogItem { ItemId = "BD-D1152", Description = "TOTE, STORAGE, NATIONAL STANDARD, 20-30 GAL, W/LID, 28.55in x 19.61in x 15.27in", UoM = "Ea", Category = "Short NSAL " },
                new CatalogItem { ItemId = "BD-D1152N", Description = "TOTE, STORAGE, NON-STANDARD", UoM = "Ea", Category = "NSAL " },
                new CatalogItem { ItemId = "Trl-060", Description = "Towel and wash cloth, personal", UoM = "ea", Category = " " },
                new CatalogItem { ItemId = "BD-D1154", Description = "Toy, Bear, Stuffed -IKD", UoM = "ea", Category = "NSAL IKD " },
                new CatalogItem { ItemId = "SS-KD218", Description = "TOY, CHILDREN PLAY KIT", UoM = "Ea", Category = "DAT NSAL " },
                new CatalogItem { ItemId = "BD-D1153", Description = "TOY, MICKEY MOUSE PLUSH, STUFFED--IKD REIMBURSEMENT PROG APPLIES", UoM = "Ea", Category = "Short DAT NSAL IKD " },
                new CatalogItem { ItemId = "BD-D1153N", Description = "TOY, STUFFED ANIMAL-NON STANDARD", UoM = "Ea", Category = "DAT " },
                new CatalogItem { ItemId = "OS-320193A", Description = "Vest Disaster services small", UoM = "ea", Category = "NSAL " },
                new CatalogItem { ItemId = "D600017ZRC", Description = "Vest, DAT vest, size Reg,special order", UoM = "ea", Category = "Short " },
                new CatalogItem { ItemId = "D600017ZXL", Description = "Vest, DAT vest, size XL, special order", UoM = "ea", Category = "Short " },
                new CatalogItem { ItemId = "OS-320194", Description = "VEST, DISASTER RELIEF OPERATIONS, DISASTER ONLY-PKG/10", UoM = "Ea", Category = "Short NSAL " },
                new CatalogItem { ItemId = "OS-321193A", Description = "VEST, DISASTER SERVICES, LARGE", UoM = "ea", Category = "NSAL " },
                new CatalogItem { ItemId = "OS-320192A", Description = "VEST, DISASTER SERVICES, LONG", UoM = "Ea", Category = "NSAL " },
                new CatalogItem { ItemId = "OS-320193B", Description = "VEST, DISASTER SERVICES, LONG 07/04 PKG/10", UoM = "ea", Category = "NSAL " },
                new CatalogItem { ItemId = "Trl-050", Description = "Vest, mesh safety, non-Red Cross", UoM = "ea", Category = "Trl " },
                new CatalogItem { ItemId = "KF-DH20B", Description = "WATER BULK", UoM = "Ea", Category = " " },
                new CatalogItem { ItemId = "KF-DH20A", Description = "WATER SINGLES", UoM = "Ea", Category = "Short Trl DAT " },
                new CatalogItem { ItemId = "Trl-015", Description = "Wheel Chocks, molded rubber w/steel grab", UoM = "ea", Category = "Trl " },
                new CatalogItem { ItemId = "PC-003", Description = "Workbook - My Preparedness", UoM = "ea", Category = "Prep " },
                new CatalogItem { ItemId = "SS-D51", Description = "Zip Ties", UoM = "pks", Category = "NSAL " }

                    );
                context.SaveChanges();
            }
        }

    } // eo CatalogItemSeedData class -------------------------------------------------------------
}// eo namespace
